name: redux_future
description: A Redux Middleware for handling Dart Futures as actions
version: 0.1.4
homepage: https://github.com/brianegan/redux_future

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  redux: ">=5.0.0"

dev_dependencies:
  test: ^1.24.6
